"""Regenerate docs/inventory/crusader.md and docs/inventory/bastion.md, read-only.

    python -I tools/inventory.py            both machines
    python -I tools/inventory.py crusader   one of them
    python -I tools/inventory.py bastion

The collectors are tools/inventory-crusader.ps1 (local PowerShell) and tools/inventory-bastion.sh (piped to
`ssh jamescron@crusade-bastion bash -s`). Both only read. Raw output goes to docs/inventory/raw/ (gitignored); the
committed .md is redacted by secret_scan.redact(). Never hand-edit the .md files: rerun this.
BRIEF 01. After Sea's machine_inventory.ps1 (github.com/seatemplar10-dev/Horse-Inner-workings), rewritten here.
"""
import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from secret_scan import redact  # noqa: E402

REPO = os.path.dirname(HERE)
OUT = os.path.join(REPO, "docs", "inventory")
RAW = os.path.join(OUT, "raw")
BASTION = "jamescron@crusade-bastion"
HEADER = "<!-- generated by tools/inventory.py on %s: do not edit by hand, rerun it -->\n\n"


def table(rows, cols):
    if not rows:
        return "_none_\n"
    esc = lambda v: str(v if v is not None else "").replace("|", "\\|").replace("\n", " ")
    lines = ["| " + " | ".join(cols) + " |", "|" + "---|" * len(cols)]
    lines += ["| " + " | ".join(esc(r.get(c, "")) for c in cols) + " |" for r in rows]
    return "\n".join(lines) + "\n"


def block(text):
    return "```\n%s\n```\n" % (text or "").strip()


def crusader():
    ps1 = os.path.join(HERE, "inventory-crusader.ps1")
    p = subprocess.run(["powershell.exe", "-NoProfile", "-ExecutionPolicy", "Bypass", "-File", ps1],
                       capture_output=True, text=True, encoding="utf-8", errors="replace", timeout=900)
    raw = p.stdout.strip().replace("\\r\\n", "\\n")  # PowerShell's Out-String ends lines with CRLF
    with open(os.path.join(RAW, "crusader.json"), "w", encoding="utf-8") as f:
        f.write(raw)
    d = json.loads(raw)
    o = d["os"]
    md = [HEADER % d["generated"], "# Crusader inventory\n\n"]
    md.append("## OS and hardware\n%s\n" % table([o], ["host", "caption", "version", "build", "installed",
                                                      "last_boot", "cpu", "ram_gb"]))
    md.append("GPU: %s\n\n" % ", ".join(o.get("gpu") or []))
    md.append("## Volumes\n%s\n" % table(d["volumes"], ["letter", "label", "fs", "size_gb", "free_gb", "health"]))
    md.append("Google Drive (G:) mounted: %s (virtual drive, not in the volume list)\n\n" % d["google_drive"]["present"])
    md.append("## Physical disks\n%s\n" % table(d["disks"], ["model", "media", "bus", "size_gb", "health"]))
    md.append("## Startup items\n%s\n" % table(d["startup"], ["name", "enabled", "command", "location"]))
    md.append("## Scheduled tasks (outside \\Microsoft\\)\n%s\n" % table(
        d["scheduled_tasks"], ["task", "state", "last_run", "last_result", "next_run", "action"]))
    md.append("## Services (third-party, plus Auto services that are stopped)\n%s\n" % table(
        d["services"], ["name", "display", "state", "start", "path"]))
    dk = d["docker"]
    md.append("## Docker\n%s\n" % table([dk], ["cli", "service", "desktop_running", "pipe_docker_engine",
                                               "pipe_desktop_linux", "server"]))
    md.append("Context:\n%s\nContainers:\n%s\nVolumes:\n%s\n" % (block(dk.get("context")), block(dk.get("containers")),
                                                               block(dk.get("volumes"))))
    md.append("## WSL\n%s\n" % block(d["wsl"] or "not installed"))
    md.append("## Tailscale\n%s\n" % block(d["tailscale"]))
    md.append("## Repos under C:\\- Tools\\- LLM\n%s\n" % table(
        d["repos"], ["repo", "branch", "remote", "upstream", "unpushed", "unpushed_all_branches", "dirty",
                     "last_commit", "worktrees"]))
    md.append("unpushed = commits on the current branch not on its upstream (-1: no upstream); unpushed_all_branches "
              "= commits on any local branch that no remote has.\n\n")
    md.append("## F:\\Steam_Modded_Variants (names and dates only; KSP running: %s)\n%s\n" % (
        d["ksp_running"], table(d["ksp_variants"], ["name", "modified"])))
    c = d["claude_dir"]
    md.append("## ~/.claude\n%s files, %s MB. Top level: %s\n\n" % (c["files"], c["mb"], ", ".join(c["top"])))
    md.append("## Installed programs (%d; plus %d Store apps)\n%s\n" % (
        len(d["programs"]), d["store_apps_count"], table(d["programs"], ["name", "version", "publisher", "installed"])))
    return redact("".join(md))


def bastion():
    with open(os.path.join(HERE, "inventory-bastion.sh"), encoding="utf-8") as f:
        script = f.read().replace("\r", "")  # a CRLF script breaks bash (see BRIEF 01's backup finding)
    # bytes, not text: Windows text-mode stdin turns every LF into CRLF on the way to bash
    p = subprocess.run(["ssh", "-o", "BatchMode=yes", "-o", "ConnectTimeout=15", BASTION, "bash", "-s"],
                       input=script.encode("utf-8"), capture_output=True, timeout=900)
    raw, err = p.stdout.decode("utf-8", "replace"), p.stderr.decode("utf-8", "replace")
    if p.returncode != 0 and not raw:
        raise SystemExit("bastion: ssh failed (%s): %s" % (p.returncode, err.strip()[:300]))
    with open(os.path.join(RAW, "bastion.txt"), "w", encoding="utf-8") as f:
        f.write(raw)
    sections, name = {}, None
    for line in raw.splitlines():
        if line.startswith("=== "):
            name = line[4:].strip()
            sections[name] = []
        elif name:
            sections[name].append(line)
    get = lambda k: "\n".join(sections.get(k, [])).strip()
    md = [HEADER % get("generated"), "# Bastion inventory\n\n"]
    titles = [("host", "Host"), ("disks", "Disks"), ("df", "Free space"), ("fstab", "fstab mounts (mount, fs, options)"),
              ("smart", "SMART"), ("memory", "Memory"), ("backups", "Backups on /mnt/backups"),
              ("line_endings", "Scripts with CRLF line endings (they break under bash)"),
              ("containers", "Containers"), ("compose_dirs", "Compose projects"), ("volumes", "Docker volumes"),
              ("docker_df", "Docker disk use"), ("tailscale_serve", "Tailscale serve"), ("ports", "Listening ports"),
              ("services", "Running services"), ("failed", "Failed units"), ("timers", "systemd timers"),
              ("cron_user", "jamescron's crontab"), ("cron_system", "System cron"), ("home", "Home folder"),
              ("sizes", "Sizes"), ("secrets_by_path", "Secrets, named by path only (never read)"),
              ("packages", "Packages (dpkg count; snaps)"), ("updates", "Reboot required")]
    for k, t in titles:
        md.append("## %s\n%s\n" % (t, block(get(k) or "(empty)")))
    if err.strip():
        md.append("## Collector errors\n%s\n" % block(err.strip()[:3000]))
    return redact("".join(md))


def main(argv):
    os.makedirs(RAW, exist_ok=True)
    targets = argv or ["crusader", "bastion"]
    for t in targets:
        md = {"crusader": crusader, "bastion": bastion}[t]()
        path = os.path.join(OUT, t + ".md")
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(md)
        print("wrote", os.path.relpath(path, REPO), len(md), "chars")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
